
const Services = [
    {
        Id: '1',
        sImgS:'images/service-single/graphics/img-1.jpg',
        sTitle: 'Création de sites web sur mesure',
        description: 'Conception et développement de sites web personnalisés, optimisés pour le SEO et adaptés à tous les appareils.',
        des2: 'J\'utilise des technologies comme HTML5, CSS3, JavaScript, et des frameworks comme React ou Vue.js.',
        des3: 'Vous bénéficiez d\'un site performant, sécurisé et compatible sur tous les navigateurs et appareils.',
        icon:'flaticon-vector',
        ssImg1:'images/service-single/graphics/img-2.jpg',
        ssImg2:'images/service-single/graphics/img-3.jpg',
    },
    {
        Id: '2',
        sImgS:'images/service-single/brand/img-1.jpg',
        sTitle: 'Développement d\'applications web',
        description: 'Conception d\'applications web interactives avec des frameworks comme React et Node.js pour des performances optimales.',
        des2: 'Je développe des applications robustes et évolutives adaptées aux besoins de vos utilisateurs.',
        des3: 'De la conception à la mise en production, je m\'assure que votre application web fonctionne sans accroc.',
        icon:'flaticon-palette',
        ssImg1:'images/service-single/brand/img-2.jpg',
        ssImg2:'images/service-single/brand/img-3.jpg',
    },
    {
        Id: '3',
        sImgS:'images/service-single/ux/img-1.jpg',
        sTitle: 'Maintenance et optimisation de sites web',
        description: 'Amélioration des performances, de la sécurité, et gestion des mises à jour pour assurer la pérennité de votre site.',
        des2: 'Je propose des audits complets et des recommandations pour optimiser votre site web.',
        des3: 'Votre site restera toujours à jour et performant grâce à une maintenance continue.',
        icon:'flaticon-add',
        ssImg1:'images/service-single/ux/img-3.jpg',
        ssImg2:'images/service-single/ux/img-3.jpg',
    },
    {
        Id: '4',
        sImgS:'images/service-single/development/img-1.jpg',
        sTitle: 'Conception de systèmes de gameplay',
        description: 'Développement de mécaniques de jeu interactives et immersives pour offrir des expériences captivantes.',
        des2: 'Création de systèmes de progression, de combat et d\'interactions dynamiques avec des moteurs comme Unity, Unreal Engine, ainsi que des scripts en LUA et SQF.',
        des3: 'Mon objectif est de créer des jeux captivants grâce à des mécaniques de gameplay fluides et équilibrées, quel que soit le moteur ou le langage utilisé.',
        icon:'flaticon-coding',
        ssImg1:'images/service-single/development/img-2.jpg',
        ssImg2:'images/service-single/development/img-3.jpg',
    },
    {
        Id: '5',
        sImgS:'images/service-single/app/img-1.jpg',
        sTitle: 'Création de scripts d\'IA et d\'événements',
        description: 'Programmation de comportements d\'IA et d\'événements pour enrichir l\'expérience de jeu, en utilisant notamment LUA et SQF.',
        des2: 'Je développe des scripts d\'IA et des événements dynamiques en LUA pour des jeux comme Garry\'s Mod ou SQF pour des environnements comme ARMA 3.',
        des3: 'L\'IA de vos jeux vidéo sera capable de s\'adapter aux actions du joueur pour une expérience immersive, quel que soit le moteur de jeu utilisé.',
        icon:'flaticon-app-development',
        ssImg1:'images/service-single/app/img-2.jpg',
        ssImg2:'images/service-single/app/img-3.jpg',
    },
    {
        Id: '6',
        sImgS:'images/service-single/softwere/img-1.jpg',
        sTitle: 'Optimisation des performances de jeu',
        description: 'Amélioration de l\'efficacité du moteur de jeu Unreal et optimisation des scripts en LUA et SQF pour une expérience fluide.',
        des2: 'Je réduis les temps de chargement, optimise les graphismes et les scripts pour que vos jeux tournent efficacement sur toutes les plateformes.',
        des3: 'Le résultat : des performances optimales, que ce soit pour des jeux sur Unity, Unreal, ou des systèmes basés sur LUA et SQF.',
        icon:'flaticon-smartphone',
        ssImg1:'images/service-single/softwere/img-2.jpg',
        ssImg2:'images/service-single/softwere/img-3.jpg',
    },
    {
        Id: '7',
        sImgS:'images/service-single/sm/img-1.jpg',
        sTitle: 'Développement d\'applications mobiles',
        description: 'Création d\'applications pour Android et iOS, utilisant Swift ou React Native pour des performances optimales.',
        des2: 'Je conçois des applications rapides, réactives et optimisées pour chaque plateforme mobile.',
        des3: 'Les applications que je développe offrent une expérience utilisateur fluide et intuitive.',
        icon:'flaticon-social-media',
        ssImg1:'images/service-single/sm/img-2.jpg',
        ssImg2:'images/service-single/sm/img-3.jpg',
    },
    {
        Id: '8',
        sImgS:'images/service-single/dm/img-1.jpg',
        sTitle: 'Intégration d\'API et de services tiers',
        description: 'Connexion d\'applications mobiles à des services externes comme des API REST pour enrichir les fonctionnalités.',
        des2: 'J\'intègre des services comme des systèmes de paiement, géolocalisation, ou gestion des utilisateurs pour enrichir vos applications mobiles.',
        des3: 'L\'intégration se fait de manière transparente pour offrir une expérience utilisateur cohérente et riche.',
        icon:'flaticon-promotion',
        ssImg1:'images/service-single/dm/img-2.jpg',
        ssImg2:'images/service-single/dm/img-3.jpg',
    },
    {
        Id: '9',
        sImgS:'images/service-single/email/img-1.jpg',
        sTitle: 'Maintenance et mise à jour des applications',
        description: 'Gestion des correctifs, des mises à jour de versions et optimisation pour les nouvelles versions des systèmes d’exploitation.',
        des2: 'Je veille à ce que vos applications mobiles restent à jour avec les dernières technologies et optimisations.',
        des3: 'Les utilisateurs profiteront toujours d\'une application performante, sécurisée et conforme aux standards actuels.',
        icon:'flaticon-email-marketing',
        ssImg1:'images/service-single/email/img-2.jpg',
        ssImg2:'images/service-single/email/img-3.jpg',
    },
]    

export default Services;